#!/bin/sh
export MPLBACKEND=Agg
export "PYTHONPATH=../mlib"
echo "CONDA_HOME in dnn is:"$CONDA_HOME
if [ -z "${CONDA_HOME}" ]; then
  CONDA_HOME="$HOME/miniconda3"
fi
if [ -d "$CONDA_HOME" ]; then
    exec "$CONDA_HOME/envs/dnn39/bin/python" "boot.py" "$@"
else
    if test -f "/matt/dnn"; then
      cd /matt/dnn
      exec python boot.py "$@"
    else
      exec /om2/user/mjgroth/miniconda3/envs/dnn39 boot.py "$@"
    fi


fi

