#!/bin/sh
export MPLBACKEND=Agg
export "PYTHONPATH=../mlib"
echo "CONDA_HOME in dnn is:"$CONDA_HOME
if [ -z "${CONDA_HOME}" ]; then
  CONDA_HOME="$HOME/miniconda3"
fi
if [ -d "$CONDA_HOME" ]; then
    exec "$CONDA_HOME/envs/dnn/bin/python" "boot.py" "$@"
else
    bash
    exec python boot.py "$@"
fi

