#!/bin/sh
"""exec" "$HOME/miniconda3/envs/dnn/bin/python" "$0" "$@"""

from lib.makereport_lib import upload_webpage, RESOURCES_ROOT
from lib.web import HTML, HTMLImage, Div, Hyperlink, HTMLProgress, HTMLLabel, Span, Br, HTMLFigure, HTMLFigCaption, TextArea, P
from lib.wolf.wolfpy import WOLFRAM
import urllib.parse



from mlib.boot.mutil import listitems
VERSIONS = {
    '1.0.0': 'First-Release',
    '1.0.1': 'Fix Grammar',
    '1.0.2': 'improve instructions: R/L Arrow Key',
    '1.1.0': 'Allow copy and pasting data',
    '1.1.1': 'Add version label'
}
THIS_VERSION = listitems(VERSIONS)[-1]

print(upload_webpage(
    HTML(
        Div(
            Span(
                HTMLLabel(
                    label='Progress: ',
                    forr='prog',
                    style='font-size: large;'
                ),
                HTMLProgress(
                    value=0,
                    maxx=0,
                    id='prog',
                    style='background-color: red;'
                ),
                clazz='center',
                style='width:100%'
            ),
            Div(f'''
        Welcome to our symmetry detection experiment (version:{THIS_VERSION[0]})!
        Before continuing, please:\n
        \t1. Make your browser fullscreen.
        \t2. Ensure you have 10 minutes to focus on the experiment without distraction. 
        
        This experiment has no sound.
        Press SPACE when you are ready to begin.
        ''',
                clazz='center',
                id='text',
                style='width:100%;font-size: large;'
                ),
            HTMLImage(
                "",
                clazz='pixel center',
                # style='width: auto; height: 100%;',
                id='im',
                style='display:none;width: 224px; height: 224px;'
            ),
            Div(
                Br,
                Div(
                    HTMLFigure(
                        HTMLFigCaption("Example of an ASYMMETRIC image (hit LEFT arrow key)",
                                       style='font-size: large;'),
                        HTMLImage(
                            RESOURCES_ROOT + "Symmetry/Exp1/NS4/sym1.png",
                            clazz='pixel',
                            style='width: 224px; height: 224px; padding: 20px;',
                            # id='ExampleNS'
                        ),
                        style='display: inline-block;'
                    ),
                    HTMLFigure(
                        HTMLFigCaption("Example of an SYMMETRIC image (hit RIGHT arrow key)",
                                       style='font-size: large;'),
                        HTMLImage(
                            RESOURCES_ROOT + "Symmetry/Exp1/S4/sym0.png",
                            clazz='pixel',
                            style='width: 224px; height: 224px; padding: 20px;',
                            # id='ExampleS'
                        ),
                        style='display: inline-block;'
                    ),
                ),
                clazz='center',
                id='examples',
                style='display:none;width:100%'
            ),
            Hyperlink(
                label="Click here to automatically open a pre-filled email",
                url=f"mailto:mjgroth@mit.edu,dsinha@bbns.org?subject=SymTest{urllib.parse.quote(THIS_VERSION[0])}&",
                clazz='center',
                id='link',
                style='display: none;font-size: large;'
            ),
            P(
                THIS_VERSION[0],
                id='VERSION',
                style='display: none;font-size: large;'
            ),
            P(
                RESOURCES_ROOT,
                id='RESOURCES_ROOT',
                style='display: none;font-size: large;'
            ),
            TextArea(
                clazz='center',
                id='textarea',
                style='display: none;font-size: small;height: 700px;text-align: left;'
            ),
            clazz='center',
            style='width: 1200px;font-size: large;'
        ),
        js='''

var perm = `S4/sym6.png
NS4/sym75.png
NS4/sym83.png
S4/sym32.png
S4/sym16.png
S4/sym54.png
NS4/sym47.png
S4/sym70.png
S4/sym72.png
NS4/sym53.png
NS4/sym85.png
NS4/sym7.png
NS4/sym11.png
NS4/sym59.png
S4/sym94.png
S4/sym58.png
S4/sym62.png
S4/sym24.png
S4/sym86.png
NS4/sym99.png
S4/sym88.png
S4/sym38.png
NS4/sym73.png
NS4/sym25.png
S4/sym40.png
NS4/sym77.png
NS4/sym1.png
NS4/sym71.png
S4/sym10.png
NS4/sym9.png
NS4/sym95.png
S4/sym48.png
NS4/sym93.png
NS4/sym57.png
NS4/sym3.png
NS4/sym5.png
NS4/sym27.png
S4/sym34.png
S4/sym18.png
NS4/sym17.png
NS4/sym55.png
NS4/sym35.png
NS4/sym37.png
S4/sym60.png
S4/sym44.png
S4/sym22.png
S4/sym78.png
NS4/sym89.png
NS4/sym45.png
NS4/sym81.png
NS4/sym61.png
NS4/sym39.png
S4/sym46.png
NS4/sym51.png
S4/sym82.png
NS4/sym69.png
NS4/sym33.png
NS4/sym67.png
S4/sym80.png
S4/sym98.png
NS4/sym87.png
S4/sym90.png
S4/sym92.png
NS4/sym65.png
NS4/sym13.png
NS4/sym97.png
NS4/sym15.png
S4/sym42.png
S4/sym96.png
S4/sym84.png
S4/sym12.png
S4/sym52.png
S4/sym14.png
S4/sym68.png
NS4/sym49.png
S4/sym28.png
S4/sym64.png
NS4/sym63.png
NS4/sym91.png
S4/sym20.png
S4/sym8.png
NS4/sym43.png
NS4/sym29.png
S4/sym50.png
S4/sym26.png
S4/sym2.png
S4/sym30.png
S4/sym76.png
NS4/sym31.png
NS4/sym19.png
S4/sym56.png
NS4/sym79.png
NS4/sym23.png
S4/sym36.png
S4/sym4.png
NS4/sym41.png
S4/sym74.png
NS4/sym21.png
S4/sym66.png
S4/sym0.png`;

perm = perm.split("\\n")


perm = perm.slice(1,5) // for prototyping


seq = ['An image that is either symmetric or asymmetric will briefly flash on the screen. If you think the image is symmetric, press the RIGHT ARROW KEY. If you think it is asymmetric, press the LEFT ARROW KEY. Some of the images will only be visible for a very small time interval and will be very difficult to see. Do not worry, this is by design. If you are not sure if it was symmetric or asymmetric, simply guess. 100 images will be shown, and then you will be done. Press SPACE to begin.']

seq = seq.concat(perm)

// If I edit this, I need to also edit the switcher below
seq = seq.concat(['Thank you so much for participating! Click the link below to open a pre-filled email for sending results and feedback, or alternatively you may copy and paste the same content from below and email it to mjgroth@mit.edu and dsinha@bbns.org'])

var i = -1
var readyToAdvance = true
var readyForChoice = false

const choices = []

const times = [100,200,300,400,500]
var nextSymTime = 0
var nextAsymTime = 0
const usedTimes = []

function showI(i) {
    console.log('showI')
    let thing = seq[i]
    if (!thing.includes("Thank you") && !thing.includes('.png')) {
        console.log('isString')
        // document.getElementById("im").style.visibility = "hidden"
        document.getElementById("im").style.display = "none"
        document.getElementById("text").style.display = "block"
        document.getElementById("text").innerHTML = thing
        
        if (i == 0) {
            console.log('showing examples')
            document.getElementById("examples").style.display = "block"
        } else {
            console.log('hiding examples')
            document.getElementById("examples").style.display = "none"
        }
        
        readyToAdvance = true
    } else if (thing.includes(".png")) {
        console.log('hiding examples')
        document.getElementById("examples").style.display = "none"
        if (thing.includes("NS")) {
            t = times[nextAsymTime]
            usedTimes.push(t)
            nextAsymTime += 1
            if (nextAsymTime == times.length) {nextAsymTime = 0}
        } else {
            t = times[nextSymTime]
            usedTimes.push(t)
            nextSymTime += 1
            if (nextSymTime == times.length) {nextSymTime = 0}
        }
        document.getElementById("text").style.display = "none"
        let RESOURCES_ROOT = document.getElementById("RESOURCES_ROOT").innerHTML
        document.getElementById("im").src=RESOURCES_ROOT+"Symmetry/Exp1/" + thing;
        setTimeout(function(){ 
            setTimeout(function(){ 
                document.getElementById("im").style.display = "none"
                document.getElementById("text").innerHTML = "Asymmetric<- ->Symmetric"
                document.getElementById("text").style.display = "block"
                readyForChoice = true
            }, t);
            // document.getElementById("im").style.visibility = "visible"
            document.getElementById("im").style.display = "block"
        }, 1000);
    } else {
        document.getElementById("im").style.display = "none"
        document.getElementById("text").style.display = "block"
        document.getElementById("text").innerHTML = thing
        
        let data = perm.map(function(e, i) {
          return "\\t" + e + '|' + usedTimes[i].toString() + "=" + choices[i] + "\\n"
        }).join("");
        
        let template = `--FEEDBACK--
    Please write any feedback here
    
--DATA-- (please do not edit below this line)\\n` + data
        
        document.getElementById("link").href = document.getElementById("link").href + "body=" + encodeURI(template)
        document.getElementById("link").style.display = "block"
        
        let VERSION = document.getElementById("VERSION").innerHTML
        
        template = VERSION + "\\n" + template
        
        document.getElementById("textarea").innerHTML = template
        document.getElementById("textarea").style.display = "block"
    }
}

window.onload = function() {
    document.getElementById("prog").max = perm.length
    // document.getElementById("im").style.visibility = "hidden"
    document.getElementById("im").style.display = "none"
    document.addEventListener('keyup', event => {
      console.log(event.key + ' pressed')
      if (event.keyCode == 32 && readyToAdvance) {
        i = i + 1
        readyToAdvance = false
        showI(i)
      }
      else if (event.key == 'ArrowLeft' && readyForChoice) {
        i = i + 1
        choices.push(event.key)
        document.getElementById("prog").value += 1
        readyForChoice = false
        showI(i)
      }
      else if (event.key == 'ArrowRight' && readyForChoice) {
        i = i + 1
        choices.push(event.key)
        document.getElementById("prog").value += 1
        readyForChoice = false
        showI(i)
      }
    })
}



        '''
    ),
    "Symmetry/Exp1",
    "Public",
    # resource_folder='_images_human/TimePilot'
    DEV=False
))

WOLFRAM.terminate()

if False:
    import numpy as np
    perm = np.random.permutation(100)
    for p in perm:
        for fold in Folder('_images_human/TimePilot').listmfiles():
            for file in fold.listmfiles():
                if file.name == f'sym{p}.png':
                    print(f'{file.parentFile.name}/{file.name}')
